#!/bin/bash

# Concatenate a few videos without re-encoding
set -eou pipefail

output=$1
shift
inputs=$@

rcd-ffm \
    -f concat -safe 0 \
    -i <(for f in $inputs; do echo "file '$PWD/$f'"; done) \
    -c copy $output

